repos:
  # prek builtin hooks: https://prek.j178.dev/builtin/#2-explicit-builtin-repository
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-json5
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/crate-ci/typos
    rev: v1.44.0
    hooks:
      - id: typos

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-renovate
        args: ["--verbose"]
        additional_dependencies: ["json5"]
